[MB] Add docker image caching

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,36 +13,30 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: brpaz/hadolint-action@v1.2.1
-      with:
-        dockerfile: ./Dockerfile
+        with:
+          dockerfile: ./Dockerfile
   build-and-push:
     runs-on: ubuntu-latest
     needs: [lint]
     steps:
-      - name: Check Out Repo
+      - name: Checkout repository
         uses: actions/checkout@v2
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v1
-
-      - name: Build and push
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
-          context: ./
-          file: ./Dockerfile
-          push: true
-          tags: ${IMAGE_NAME}
-          
-      - name: Image digest
-        run: echo ${{ steps.docker_build.outputs.digest }}
+  
+      - name: Create release file (git revision info)
+        run: |
+          echo -e "sha: ${GITHUB_SHA}\ntag: ${GITHUB_REF}" # For debugging
+          echo -e "git:\n  sha: ${GITHUB_SHA}\n  tag: ${GITHUB_REF}" > release.yml
+      - name: Build and Upload Image
+        env:
+          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+          DOCKER_REGISTRY_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+        run: |
+          timestamp=$(date +"%Y%m%d%H%M")
+          docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_ACCESS_TOKEN
+          docker pull $IMAGE_NAME || echo "Failed to pull $IMAGE_NAME image - Building from scratch"
+          docker build --cache-from $IMAGE_NAME -t $IMAGE_NAME:${GIT_SHA::8} -t $IMAGE_NAME:$timestamp -t $IMAGE_NAME:latest .
+          docker push $IMAGE_NAME 
+            
   deploy?:
     runs-on: ubuntu-latest
     steps:
